import { useEffect, useRef, useState } from 'react'
import QRCode from 'qrcode'
import { ensureGuestSession, supabase } from './lib/supabase'

type Language = 'en' | 'ha' | 'yo' | 'ig'
type FriendQuestion = { id:string; prompt:string; options:string[]; question_type:'multiple_choice'|'riddle'|'scramble'; metadata?:Record<string,unknown> }
type Challenge = { id:string; invite_code?:string; language:Language; duration_seconds:number; status:string; started_at?:string; expires_at?:string; creator_id?:string; opponent_id?:string|null }

async function call<T>(name:string, body:Record<string,unknown>):Promise<T>{await ensureGuestSession();const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Could not create a player session.');const {data,error}=await supabase.functions.invoke(name,{body,headers:{Authorization:`Bearer ${session.access_token}`}});if(error)throw error;return data as T}

export default function FriendMode({language,onBack,onNeedAuth}:{language:Language;onBack:()=>void;onNeedAuth?:()=>void}){
 const [view,setView]=useState<'menu'|'waiting'|'game'|'result'>('menu');const [challenge,setChallenge]=useState<Challenge|null>(null);const [playerId,setPlayerId]=useState('');const [code,setCode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [question,setQuestion]=useState<FriendQuestion|null>(null);const [position,setPosition]=useState(1);const [score,setScore]=useState(0);const [otherScore,setOtherScore]=useState(0);const [remaining,setRemaining]=useState(90);const [selected,setSelected]=useState<string|null>(null);const [correct,setCorrect]=useState<boolean|null>(null);const [winner,setWinner]=useState<string|null>(null);const [finished,setFinished]=useState(false);const qrRef=useRef<HTMLCanvasElement|null>(null)
 const authFail=(e:unknown)=>{const message=e instanceof Error?e.message:'Guest play is unavailable.';setError(message);if(/anonymous sign-ins are disabled|player session/i.test(message))onNeedAuth?.()}
 useEffect(()=>{void (async()=>{try{await ensureGuestSession();const {data:{user}}=await supabase.auth.getUser();if(user)setPlayerId(user.id)}catch(e){authFail(e)}})();const incoming=new URLSearchParams(window.location.search).get('challenge');if(incoming){setCode(incoming.toUpperCase());setError('Challenge link detected. Join below.')}},[onNeedAuth])
 useEffect(()=>{if(view!=='waiting'||!challenge?.invite_code||!qrRef.current)return;const url=`${window.location.origin}${window.location.pathname}?challenge=${challenge.invite_code}`;void QRCode.toCanvas(qrRef.current,url,{width:176,margin:1,color:{dark:'#11110f',light:'#f3eee2'}}).catch(()=>setError('QR code could not be generated.'))},[view,challenge?.invite_code])
 const reset=()=>{setChallenge(null);setQuestion(null);setPosition(1);setScore(0);setOtherScore(0);setRemaining(90);setSelected(null);setCorrect(null);setWinner(null);setFinished(false);setError('');setCode('');window.history.replaceState({},'',window.location.pathname);setView('menu')}
 const enterGame=async(c:Challenge)=>{setChallenge(c);setRemaining(Math.max(0,Math.ceil((Date.parse(c.expires_at||'')-Date.now())/1000)));setPosition(1);setFinished(false);setView('game');await loadQuestion(c.id,1)}
 const startGame=async(c:Challenge)=>{setBusy(true);setError('');try{const data=await call<{challenge:Challenge}>('start_friend_challenge',{challenge_id:c.id});await enterGame(data.challenge)}catch(e){authFail(e)}finally{setBusy(false)}}
 const loadQuestion=async(id:string,pos:number)=>{try{const data=await call<{question:FriendQuestion;position:number;expires_at:string}>('get_friend_question',{challenge_id:id,position:pos});setQuestion(data.question);setPosition(data.position);setSelected(null);setCorrect(null)}catch(e){const message=e instanceof Error?e.message:'Could not load question.';if(/no more|expired/i.test(message))void finish(id);else authFail(e)}}
 const create=async()=>{setBusy(true);setError('');try{const data=await call<{challenge:Challenge}>('create_friend_challenge',{language,duration_seconds:90});setChallenge(data.challenge);setCode(data.challenge.invite_code||'');setView('waiting')}catch(e){authFail(e)}finally{setBusy(false)}}
 const join=async()=>{const clean=code.trim().toUpperCase();if(clean.length<6)return setError('Enter a valid challenge code.');setBusy(true);setError('');try{const data=await call<{challenge:Challenge}>('join_friend_challenge',{invite_code:clean});setChallenge(data.challenge);setCode(clean);setView('waiting')}catch(e){authFail(e)}finally{setBusy(false)}}
 const findRival=async()=>{setBusy(true);setError('');try{const data=await call<{status:'waiting'|'matched';challenge?:Challenge}>('find_rival',{language});if(data.status==='matched'&&data.challenge)await startGame(data.challenge);else setView('waiting')}catch(e){authFail(e)}finally{setBusy(false)}}
 const finish=async(id:string)=>{if(finished)return;setFinished(true);try{const data=await call<{creator_score:number;opponent_score:number;winner_id:string|null}>('finish_friend_challenge',{challenge_id:id});setScore(data.creator_score);setOtherScore(data.opponent_score);setWinner(data.winner_id);setQuestion(null);setView('result')}catch(e){setFinished(false);setError(e instanceof Error?e.message:'Could not finish challenge.')}}
 const answer=async(option:string)=>{if(!challenge||!question||selected||finished)return;setSelected(option);setBusy(true);setError('');try{const data=await call<{correct:boolean;score:number}>('submit_friend_answer',{challenge_id:challenge.id,position,answer:option});setCorrect(data.correct);setScore(data.score);window.setTimeout(()=>{if(Date.parse(challenge.expires_at||'')<=Date.now())void finish(challenge.id);else void loadQuestion(challenge.id,position+1)},data.correct?450:750)}catch(e){setSelected(null);setError(e instanceof Error?e.message:'Answer could not be submitted.')}finally{setBusy(false)}}
 useEffect(()=>{if(view!=='game'||!challenge?.expires_at||finished)return;const tick=()=>{const left=Math.max(0,Math.ceil((Date.parse(challenge.expires_at!)-Date.now())/1000));setRemaining(left);if(left===0)void finish(challenge.id)};tick();const t=window.setInterval(tick,200);return()=>window.clearInterval(t)},[view,challenge?.expires_at,challenge?.id,finished])
 useEffect(()=>{if(view!=='waiting'||!challenge||!playerId)return;const poll=async()=>{const {data}=await supabase.from('friend_challenges').select('id,creator_id,opponent_id,language,duration_seconds,status,started_at,expires_at').eq('id',challenge.id).maybeSingle();if(!data)return;setChallenge(data as Challenge);if(data.status==='active')void enterGame(data as Challenge)};const t=window.setInterval(()=>void poll(),1000);void poll();return()=>window.clearInterval(t)},[view,challenge?.id,playerId])
 const share=async()=>{if(!challenge?.invite_code)return;const url=`${window.location.origin}${window.location.pathname}?challenge=${challenge.invite_code}`;try{if(navigator.share)await navigator.share({title:'TRIVIA 9JA challenge',text:`Challenge me on TRIVIA 9JA: ${challenge.invite_code}`,url});else if(navigator.clipboard){await navigator.clipboard.writeText(url);setError('Challenge link copied.')}}catch{}}
 if(view==='game'&&challenge)return <main className="app-shell inner-screen"><header className="inner-header"><button onClick={onBack}>←</button><div><p className="eyebrow">FRIEND CHALLENGE</p><h1>{remaining}s left</h1></div><span className="coin-pill">{score} — {otherScore}</span></header><div className="game-progress"><span style={{width:`${Math.max(0,(remaining/challenge.duration_seconds)*100)}%`}}/></div>{error&&<p className="auth-message error">{error}</p>}{question?<section className="question-stage"><div className="question-meta"><span>QUESTION {position}</span><span>90 SEC</span></div><div className="question-card"><span className="question-type">{question.question_type==='riddle'?'BRAIN TEASER':question.question_type==='scramble'?'LETTER SCRAMBLE':'FRIEND DUEL'}</span><h1>{question.prompt}</h1></div><div className="answers">{question.options.map((o,i)=><button disabled={Boolean(selected)||busy} className={`answer ${selected===o?(correct?'correct':'wrong'):''}`} key={o} onClick={()=>answer(o)}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div></section>:<p className="auth-message">Finishing challenge…</p>}</main>
 if(view==='result')return <main className="app-shell inner-screen"><header className="inner-header"><button onClick={reset}>←</button><div><p className="eyebrow">FRIEND CHALLENGE</p><h1>Challenge complete.</h1></div></header><section className="friend-status"><p className="section-label">FINAL SCORE</p><h2>{score} — {otherScore}</h2><p>{winner===null?'It’s a draw.':winner===playerId?'You won.':'You lost.'}</p><button className="primary-action" onClick={reset}>PLAY AGAIN <Arrow/></button></section></main>
 return <main className="app-shell inner-screen friend-shell"><header className="inner-header"><button onClick={onBack}>←</button><div><p className="eyebrow">FRIEND MODE</p><h1>Make it personal.</h1></div></header>{error&&<p className="auth-message error">{error}</p>}<section className="friend-menu-grid"><article className="friend-tile"><span className="eyebrow">01 · PRIVATE</span><h2>Settle it properly.</h2><p>Create a private 90-second challenge and send the code to your rival.</p><button className="primary-action" disabled={busy} onClick={create}>{busy?'CREATING…':'CREATE CHALLENGE'} <Arrow/></button></article><article className="friend-tile gold"><span className="eyebrow">02 · JOIN</span><h2>Got a code?</h2><p>Enter the challenge code your friend sent you.</p><input className="friend-input" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="10-CHARACTER CODE" maxLength={10}/><button className="secondary-action" disabled={busy} onClick={join}>JOIN CHALLENGE <Arrow/></button></article><article className="friend-tile"><span className="eyebrow">03 · RIVAL</span><h2>Random opponent.</h2><p>Find someone waiting in the same language and play under the same clock.</p><button className="primary-action" disabled={busy} onClick={findRival}>{busy?'SEARCHING…':'FIND A RIVAL'} <Arrow/></button></article></section>{view==='waiting'&&challenge&&<div className="auth-backdrop"><section className="auth-card" style={{textAlign:'center'}}><p className="eyebrow">{challenge.opponent_id?'MATCH FOUND':'INVITE SENT'}</p><h2>{challenge.opponent_id?'Your rival is ready.':'Waiting for your friend.'}</h2><p className="auth-subtitle">{challenge.opponent_id?(challenge.creator_id===playerId?'Start the 90-second duel when you’re ready.':'Waiting for the challenge host to start.'):`Share code ${challenge.invite_code}.`}</p>{challenge.invite_code&&<><canvas ref={qrRef} aria-label="QR code for challenge" style={{display:'block',width:176,height:176,margin:'14px auto',borderRadius:10}}/><div className="friend-code-box"><small>YOUR CODE</small><span className="friend-code">{challenge.invite_code}</span></div><button className="secondary-action" onClick={share}>SHARE CHALLENGE</button></>}{challenge.opponent_id&&challenge.creator_id===playerId&&challenge.status==='ready'&&<button className="primary-action" disabled={busy} onClick={()=>startGame(challenge)}>{busy?'STARTING…':'START CHALLENGE'} <Arrow/></button>}<button className="secondary-action" onClick={reset}>CANCEL</button></section></div>}</main>
}
const Arrow=()=> <span className="arrow">→</span>
